In [2]:
#importing the necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#reading the csv file into a python environment
data = pd.read_csv('/content/labeledTrainData.tsv', sep="\t")

In [4]:
#checking the first few rows of the data
data.head()

       id  sentiment                                             review
0  5814_8          1  With all this stuff going down at the moment w...
1  2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...
2  7759_3          0  The film starts with a manager (Nicholas Bell)...
3  3630_4          0  It must be assumed that those who praised this...
4  9495_8          1  Superbly trashy and wondrously unpretentious 8...

In [5]:
#cheking the shape of the data
data.shape

(25000, 3)

In [6]:
#dropping column id
data.drop('id', axis=1, inplace=True)

In [7]:
#cheking the first few rows of the data
data.head()

   sentiment                                             review
0          1  With all this stuff going down at the moment w...
1          1  \The Classic War of the Worlds\" by Timothy Hi...
2          0  The film starts with a manager (Nicholas Bell)...
3          0  It must be assumed that those who praised this...
4          1  Superbly trashy and wondrously unpretentious 8...

In [8]:
#to see full column width
pd.set_option('display.max_colwidth', None)

In [9]:
data.head()

,sentiment,review
0,1,"With all this stuff going down at the moment with MJ i've started listening to his music, watching the odd documentary here and there, watched The Wiz and watched Moonwalker again. Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent. Moonwalker is part biography, part feature film which i remember going to see at the cinema when it was originally released. Some of it has subtle messages about MJ's feeling towards the press and also the obvious message of drugs are bad m'kay.<br /><br />Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring. Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him.<br /><br />The actual feature film bit when it finally starts is only on for 20 minutes or so excluding the Smooth Criminal sequence and Joe Pesci is convincing as a psychopathic all powerful drug lord. Why he wants MJ dead so bad is beyond me. Because MJ overheard his plans? Nah, Joe Pesci's character ranted that he wanted people to know it is he who is supplying drugs etc so i dunno, maybe he just hates MJ's music.<br /><br />Lots of cool things in this like MJ turning into a car and a robot and the whole Speed Demon sequence. Also, the director must have had the patience of a saint when it came to filming the kiddy Bad sequence as usually directors hate working with one kid let alone a whole bunch of them performing a complex dance scene.<br /><br />Bottom line, this movie is for people who like MJ on one level or another (which i think is most people). If not, then stay away. It does try and give off a wholesome message and ironically MJ's bestest buddy in this movie is a girl! Michael Jackson is truly one of the most talented people ever to grace this planet but is he guilty? Well, with all the attention i've gave this subject....hmmm well i don't know because people can be different behind closed doors, i know this for a fact. He is either an extremely nice but stupid guy or one of the most sickest liars. I hope he is not the latter."
1,1,"\The Classic War of the Worlds\"" by Timothy Hines is a very entertaining film that obviously goes to great effort and lengths to faithfully recreate H. G. Wells' classic book. Mr. Hines succeeds in doing so. I, and those who watched his film with me, appreciated the fact that it was not the standard, predictable Hollywood fare that comes out every year, e.g. the Spielberg version with Tom Cruise that had only the slightest resemblance to the book. Obviously, everyone looks for different things in a movie. Those who envision themselves as amateur \""critics\"" look only to criticize everything they can. Others rate a movie on more important bases,like being entertained, which is why most people never agree with the \""critics\"". We enjoyed the effort Mr. Hines put into being faithful to H.G. Wells' classic novel, and we found it to be very entertaining. This made it easy to overlook what the \""critics\"" perceive to be its shortcomings."""
2,0,"The film starts with a manager (Nicholas Bell) giving welcome investors (Robert Carradine) to Primal Park . A secret project mutating a primal animal using fossilized DNA, like ¨Jurassik Park¨, and some scientists resurrect one of nature's most fearsome predators, the Sabretooth tiger or Smilodon . Scientific ambition turns deadly, however, and when the high voltage fence is opened the creature escape and begins savagely stalking its prey - the human visitors , tourists and scientific.Meanwhile some youngsters enter in the restricted area of the security center and are attacked by a pack of large pre-historical animals which are deadlier and bigger . In addition , a security agent (Stacy Haiduk) and her mate (Brian Wimmer) fight hardly against the carnivorous Smilodons. The Sabretooths, themselves , of course, are the real star stars and they are astounding terrifyingly though not convincing. The giant animals savagely are stalking its prey and the group run afoul and fight against one nature's most fearsome predators. Furthermore a third Sabretooth more dangerous and slow stalks its victims.<br /><br />The movie delivers the goods with lots of blood and gore as beheading, hair-raising chills,full of scares when the Sabretooths appear with mediocre special effects.The story provides exciting and stirring entertainment but it results to be quite boring .The giant animals are majority made by computer generator and seem totally lousy .Middling performances though the players reacting appropriately to becoming food.Actors give vigorously physical performances dodging the beasts ,running,bound and leaps or dangling over walls . And it packs a ridiculous final deadly scene. No for small kids by realistic,gory and violent attack scenes . Other films about Sabretooths or Smilodon are the following : ¨Sabretooth(2002)¨by James R Hickox with Vanessa Angel, David Keith and John Rhys Davies and the much better ¨10.000 BC(2006)¨ by Roland Emmerich with with Steven Strait, Cliff Curtis and Camilla Belle. This motion picture filled with bloody moments is badly directed by George Miller and with no originality because takes too many elements from previous films. Miller is an Australian director usually working for television (Tidal wave, Journey to the center of the earth, and many others) and occasionally for cinema ( The man from Snowy river, Zeus and Roxanne,Robinson Crusoe ). Rating : Below average, bottom of barrel."
3,0,"It must be assumed that those who praised this film (\the greatest filmed opera ever,\"" didn't I read somewhere?) either don't care for opera, don't care for Wagner, or don't care about anything except their desire to appear Cultured. Either as a representation of Wagner's swan-song, or as a movie, this strikes me as an unmitigated disaster, with a leaden reading of the score matched to a tricksy, lugubrious realisation of the text.<br /><br />It's questionable that people with ideas as to what an opera (or, for that matter, a play, especially one by Shakespeare) is \""about\"" should be allowed anywhere near a theatre or film studio; Syberberg, very fashionably, but without the smallest justification from Wagner's text, decided that Parsifal is \""about\"" bisexual integration, so that the title character, in the latter stages, transmutes into a kind of beatnik babe, though one who continues to sing high tenor -- few if any of the actors in the film are the singers, and we get a double dose of Armin Jordan, the conductor, who is seen as the face (but not heard as the voice) of Amfortas, and also appears monstrously in double exposure as a kind of Batonzilla or Conductor Who Ate Monsalvat during the playing of the Good Friday music -- in which, by the way, the transcendant loveliness of nature is represented by a scattering of shopworn and flaccid crocuses stuck in ill-laid turf, an expedient which baffles me. In the theatre we sometimes have to piece out such imperfections with our thoughts, but I can't think why Syberberg couldn't splice in, for Parsifal and Gurnemanz, mountain pasture as lush as was provided for Julie Andrews in Sound of Music...<br /><br />The sound is hard to endure, the high voices and the trumpets in particular possessing an aural glare that adds another sort of fatigue to our impatience with the uninspired conducting and paralytic unfolding of the ritual. Someone in another review mentioned the 1951 Bayreuth recording, and Knappertsbusch, though his tempi are often very slow, had what Jordan altogether lacks, a sense of pulse, a feeling for the ebb and flow of the music -- and, after half a century, the orchestral sound in that set, in modern pressings, is still superior to this film."""
4,1,"Superbly trashy and wondrously unpretentious 80's exploitation, hooray! The pre-credits opening sequences somewhat give the false impression that we're dealing with a serious and harrowing drama, but you need not fear because barely ten minutes later we're up until our necks in nonsensical chainsaw battles, rough fist-fights, lurid dialogs and gratuitous nudity! Bo and Ingrid are two orphaned siblings with an unusually close and even slightly perverted relationship. Can you imagine playfully ripping off the towel that covers your sister's naked body and then stare at her unshaven genitals for several whole minutes? Well, Bo does that to his sister and, judging by her dubbed laughter, she doesn't mind at all. Sick, dude! Anyway, as kids they fled from Russia with their parents, but nasty soldiers brutally slaughtered mommy and daddy. A friendly smuggler took custody over them, however, and even raised and trained Bo and Ingrid into expert smugglers. When the actual plot lifts off, 20 years later, they're facing their ultimate quest as the mythical and incredibly valuable White Fire diamond is coincidentally found in a mine. Very few things in life ever made as little sense as the plot and narrative structure of \White Fire\"", but it sure is a lot of fun to watch. Most of the time you have no clue who's beating up who or for what cause (and I bet the actors understood even less) but whatever! The violence is magnificently grotesque and every single plot twist is pleasingly retarded. The script goes totally bonkers beyond repair when suddenly  and I won't reveal for what reason  Bo needs a replacement for Ingrid and Fred Williamson enters the scene with a big cigar in his mouth and his sleazy black fingers all over the local prostitutes. Bo's principal opponent is an Italian chick with big breasts but a hideous accent, the preposterous but catchy theme song plays at least a dozen times throughout the film, there's the obligatory \""we're-falling-in-love\"" montage and loads of other attractions! My God, what a brilliant experience. The original French title translates itself as \""Life to Survive\"", which is uniquely appropriate because it makes just as much sense as the rest of the movie: None!"""

In [10]:
# reducing the number of rows to 200 to reduce the size of the output later so that it can be used further in deep learning in RNN
data_reduced = data.iloc[0:200]

DATA PREPROCESSING

In [11]:
#writing the fuction to remove the punctuations
import string
def remove_punctuation(text):
  no_punctuation = "".join([i for i in text if i not in string.punctuation])
  return no_punctuation

In [12]:
#writing the fucntion to tokenize
import nltk
nltk.download('punkt')
def tokenize(text):
  words = nltk.word_tokenize(text)
  return words

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [13]:
#writing the function to remove stopwords
nltk.download('stopwords')
stopwords = nltk.corpus.stopwords.words('english')
def remove_stopwords(text):
  no_stopwords = [i for i in text if i not in stopwords]
  return no_stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [14]:
#writing the function to lemmatize
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()
def lemmatize(text):
  lemmatized_text = [lemmatizer.lemmatize(word) for word in text]
  return lemmatized_text

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [15]:
#writing the function to do all the above functions at one place
def preprocess(df_col):
  corpus =[]
  for item in df_col:
    new_item = remove_punctuation(item)
    new_item = new_item.lower()
    new_item = tokenize(new_item)
    new_item = remove_stopwords(new_item)
    new_item = lemmatize(new_item)
    corpus.append(' '.join(str(x) for x in new_item))
  return corpus

In [16]:
#saving the output into corpus
corpus = preprocess(data_reduced.review)

In [17]:
#corpus = preprocess(data.review)

In [18]:
corpus

['stuff going moment mj ive started listening music watching odd documentary watched wiz watched moonwalker maybe want get certain insight guy thought really cool eighty maybe make mind whether guilty innocent moonwalker part biography part feature film remember going see cinema originally released subtle message mjs feeling towards press also obvious message drug bad mkaybr br visually impressive course michael jackson unless remotely like mj anyway going hate find boring may call mj egotist consenting making movie mj fan would say made fan true really nice himbr br actual feature film bit finally start 20 minute excluding smooth criminal sequence joe pesci convincing psychopathic powerful drug lord want mj dead bad beyond mj overheard plan nah joe pescis character ranted wanted people know supplying drug etc dunno maybe hate mjs musicbr br lot cool thing like mj turning car robot whole speed demon sequence also director must patience saint came filming kiddy bad sequence usually director hate working one kid let alone whole bunch performing complex dance scenebr br bottom line movie people like mj one level another think people stay away try give wholesome message ironically mjs bestest buddy movie girl michael jackson truly one talented people ever grace planet guilty well attention ive gave subjecthmmm well dont know people different behind closed door know fact either extremely nice stupid guy one sickest liar hope latter',
 'classic war world timothy hines entertaining film obviously go great effort length faithfully recreate h g well classic book mr hines succeeds watched film appreciated fact standard predictable hollywood fare come every year eg spielberg version tom cruise slightest resemblance book obviously everyone look different thing movie envision amateur critic look criticize everything others rate movie important baseslike entertained people never agree critic enjoyed effort mr hines put faithful hg well classic novel found entertaining made easy overlook critic perceive shortcoming',
 'film start manager nicholas bell giving welcome investor robert carradine primal park secret project mutating primal animal using fossilized dna like ¨jurassik park¨ scientist resurrect one nature fearsome predator sabretooth tiger smilodon scientific ambition turn deadly however high voltage fence opened creature escape begin savagely stalking prey human visitor tourist scientificmeanwhile youngster enter restricted area security center attacked pack large prehistorical animal deadlier bigger addition security agent stacy haiduk mate brian wimmer fight hardly carnivorous smilodons sabretooths course real star star astounding terrifyingly though convincing giant animal savagely stalking prey group run afoul fight one nature fearsome predator furthermore third sabretooth dangerous slow stalk victimsbr br movie delivers good lot blood gore beheading hairraising chillsfull scare sabretooths appear mediocre special effectsthe story provides exciting stirring entertainment result quite boring giant animal majority made computer generator seem totally lousy middling performance though player reacting appropriately becoming foodactors give vigorously physical performance dodging beast runningbound leap dangling wall pack ridiculous final deadly scene small kid realisticgory violent attack scene film sabretooths smilodon following ¨sabretooth2002¨by james r hickox vanessa angel david keith john rhys davy much better ¨10000 bc2006¨ roland emmerich steven strait cliff curtis camilla belle motion picture filled bloody moment badly directed george miller originality take many element previous film miller australian director usually working television tidal wave journey center earth many others occasionally cinema man snowy river zeus roxannerobinson crusoe rating average bottom barrel',
 'must assumed praised film greatest filmed opera ever didnt read somewhere either dont care opera dont care wagner dont care anything except desire appear cultured either representation wagner swansong movie strike unmitigated disaster leaden reading score matched tricksy lugubrious realisation textbr br questionable people idea opera matter play especially one shakespeare allowed anywhere near theatre film studio syberberg fashionably without smallest justification wagner text decided parsifal bisexual integration title character latter stage transmutes kind beatnik babe though one continues sing high tenor actor film singer get double dose armin jordan conductor seen face heard voice amfortas also appears monstrously double exposure kind batonzilla conductor ate monsalvat playing good friday music way transcendant loveliness nature represented scattering shopworn flaccid crocus stuck illlaid turf expedient baffle theatre sometimes piece imperfection thought cant think syberberg couldnt splice parsifal gurnemanz mountain pasture lush provided julie andrew sound musicbr br sound hard endure high voice trumpet particular possessing aural glare add another sort fatigue impatience uninspired conducting paralytic unfolding ritual someone another review mentioned 1951 bayreuth recording knappertsbusch though tempo often slow jordan altogether lack sense pulse feeling ebb flow music half century orchestral sound set modern pressing still superior film',
 'superbly trashy wondrously unpretentious 80 exploitation hooray precredits opening sequence somewhat give false impression dealing serious harrowing drama need fear barely ten minute later neck nonsensical chainsaw battle rough fistfight lurid dialog gratuitous nudity bo ingrid two orphaned sibling unusually close even slightly perverted relationship imagine playfully ripping towel cover sister naked body stare unshaven genitals several whole minute well bo sister judging dubbed laughter doesnt mind sick dude anyway kid fled russia parent nasty soldier brutally slaughtered mommy daddy friendly smuggler took custody however even raised trained bo ingrid expert smuggler actual plot lift 20 year later theyre facing ultimate quest mythical incredibly valuable white fire diamond coincidentally found mine thing life ever made little sense plot narrative structure white fire sure lot fun watch time clue who beating cause bet actor understood even le whatever violence magnificently grotesque every single plot twist pleasingly retarded script go totally bonkers beyond repair suddenly \x96 wont reveal reason \x96 bo need replacement ingrid fred williamson enters scene big cigar mouth sleazy black finger local prostitute bos principal opponent italian chick big breast hideous accent preposterous catchy theme song play least dozen time throughout film there obligatory werefallinginlove montage load attraction god brilliant experience original french title translates life survive uniquely appropriate make much sense rest movie none',
 'dont know people think bad movie got pretty good plot good action change location harry hurt either sure offensive gratuitous movie like eastwood good form dirty harry liked pat hingle movie small town cop liked dirty harry see one lot better dead pool 45',
 'movie could good come way short cheesy special effect soso acting could looked past story wasnt lousy background story would better plot center around evil druid witch linked woman get migraine movie drag never clearly explains anything keep plodding christopher walken part completely senseless movie movie potential look like really bad made tv movie would avoid movie',
 'watched video friend house im glad waste money buying one video cover scene 1975 movie capricorn one movie start several clip rocket blowup related manned flight sibrels smoking gun short video clip astronaut preparing video broadcast edits voiceover instead letting u listen crew say video curiously end showing zapruder film claim radiation shielding star photography others lead believe extremely ignorant sort ax grind nasa astronaut american general science bad video',
 'friend mine bought film £1 even grossly overpriced despite featuring big name adam sandler billy bob thornton incredibly talented burt young film funny taking chisel hammering straight earhole us tired bottom barrel comedic technique consistently breaking fourth wall sandler talk audience seemingly pointless montage hot girlsbr br adam sandler play waiter cruise ship want make successful comedian order become successful woman ship resident comedian shamelessly named dickie due unfathomable success opposite gender presumed lost sea sandlers character shecker get big break dickie dead he rather locked bathroom presumably sea sickbr br perhaps mouth vomited worst film time',
 'br br movie full reference like mad max ii wild one many others ladybug´s face it´s clear reference tribute peter lorre movie masterpiece we´ll talk much future',
 'happens army wetback towelheads godless eastern european commie gather force south border gary busey kick butt course another laughable example reaganera cultural fallout bulletproof waste decent supporting cast headed l q jones thalmus rasulala',
 'although generally like remake believing remake waste time film exception didnt actually know far reading previous comment remake opinion purely actual film comparisonbr br story way written question capote need wordsbr br play anthony edward eric robert superb seen movie one certain good actor case eric always wondered sister number 1 famous star brother time certainty raised fact question play well play mr edward clearly top professionbr br recommend film top 50 film see keep dvd shelf',
 'mr harvey light candle anchored brilliant performance timothy spallbr br predict titular morose tight teacher sort break catharsis based deep secret past emotion unveiled surprising spall range feeling conveyed quite moving usually get portray part mike leigh repertorybr br expected boring school bus trip used comic purpose simpson central situation visit salisbury cathedral rhidian brook script wellcontained structured dramatic purpose almost formally divided actsbr br introduced urban british range racially religiously diverse kid uniform couldnt tell private public school gather \x96 rapping black kid serious south asian muslim white bully mean girl \x96 conveyed quite naturally individually young actor recognized british tv shameless exuberant representing usual range junior high social pressure celia imrie put warmth supervisor role martinet usually playbr br break trip lead transformative crisis others remain amusingly oblivious think like teacher portrayed ben mile coupling spoon fed didactic lesson religious tolerance much faith people well god bbc showed england easter time bbc america showed u christmasbr br nathalie press also good summer love key role mr harvey redemption could played movieoftheweek preaching touching reach unexpected way unfortunately saw intense scene interrupted commercialsbr br bit heavyhanded several time pointedly calling road trip pilgrimage quiet film best evocation good towards men ive seen holidaythemed tv movie',
 'feeling submerged one wouldnt better right must looking champagne money care final product voice get repeatedly dubbed stranger sound nothing like editing well grade amateurish nothing b cgrade movie enough money hire couple talented cameraman ok sound designerbr br like previous poster said problem seem appear postproduction voice dubbing etc bad cause plot actually ok sg flickbr br ill never rent another sg flick unless email asking forgivenessbr br bad miss kelly lebrockbr br jimbo',
 'note george litman others mystery science theater 3000 riff dont think breederbr br favorite riff looking like simply complete absurdity right well would say must give credit mst3k crew trying ridicule tv movie really cant make much fun dialog bill good playwright hand production bad even would disown junior high school drama club could betterbr br would recommend buy book read hamlet',
 'stephen king adaptation scripted king young family newcomer rural maine find pet cemetery close home father dale midkiff find micmac burial ground beyond pet cemetery power resurrection course anything buried come back quite rightbr br average horror picture start clumsy insulting inept continues way absolute worst element midkiffs worthless performance get little better toward end genuinely disturbing finale point fact whole movie really disturbing cant completely dismiss least something make memorable decent supporting performance fred gwynne wise old aged neighbor brad greenquist disfigured spirit victor pascow enough really redeem filmbr br king usual cameo ministerbr br followed sequel also directed mary lambert wonder shes mainstream film work sincebr br 410',
 'matrix exciting summer blockbuster visually fantastic also curiously thought provoking twilight zoneish manner general rule applies sequel doesnt match predecessor worse doesnt even compare itbr br reloaded explodes onto screen unprofessional fashion opening second first impression generally good one trinity shot dream immediately film nosedive disastrous first 45 minute gradually gain momentum enter matrix agent smith battle take place loses speed reach 14minute car chase sequence get even worse big groanworthy twist end worst overlong zion rave scene absolutely nothing plot also pathetic excuse porn depressive dance musicbr br bullettime aspect matrix good addition reloaded overuse make seem boring first one interesting plot turn linear remotely interesting movie basically series stylish diversion prevent u realising empty really work incorrect principle bigger better appears matrix franchise quickly descended special effect drenched misfire franchise star war saga havebr br acting standard poor part best character course go hugo weaving agent smith one slightly interesting keanu reef definitive neo special effect little room make much impact academy award nominee laurence fishburne reduced monotonous mentor poor dialogue carrie ann moss part action chick could done much better actress br br poor throwntogether movie matrix reloaded disappointment didnt like first one unlikely flock one diehard fan even movie subgenre special effect bonanza minority report matrix etc still rather poor imdb rating 4510',
 'ulli lommels 1980 film boogey man classic average low budget chiller thats worth look sequel 1983s boogey man ii ultimately waste time least entertaining one taken least bit seriously ii left door open another sequel one wouldnt minded seeing least one one day browsing though video store mall came across film entitled return boogey man found sequel earlier film happy shell buck iti known better though opening title boogey man 3 sequel two far superior film named well totally anywaybr br pro ha thats laugh anything good hunk cow dung let seeit footage boogey man umits mercifully short yeah thats itbr br con start decision decision first movie total bore go one scene next without anything remotely interesting scary happening acting stiff best actor likely friend director acting experience whatsoever probably none since plot nonexistent script shoddily written direction plain awful director try make film look artsy fartsy making camera move around light flicker filter add nothing music dull hard hear part tie original botched suzanna love character named lacey natalie event depicted beginning original take place 1978 also 3 title mention happened ii finally add nothing new interesting either series genrebr br final thought people behind waste time money ashamed one thing original film director first sucked instead supposed sequel film masterpiece damn sure far interesting entertaining ever another sequel doubt need forget one ever happened handled either lommel someone least idea make decent horror filmbr br rating 15',
 'movie one among indian movie would never fade away passage time would spell binding appeal ever diminish even indian cinema transforms abyss artificially styled pop culture drill oriented extra take enhancing pt styled film songsbr br cinematography speaks excellent skill josef werching accentuate monumental cinema scope effect film entiretybr br gone day great cinema every scene clipped many time retake taken finalizing meticulous attention paid crafting editing scene poignant scene filled sublime emotional intensity like instance meena kumari refuse say yes approval nikah marriage bond climb hill running berserk traumatized frenzy moment raj kumar follows strong gale wind blew away veil kumari onto leg kumarbr br kamal amrohi shall always remembered golden word annals indian cinema history endeavoring complete movie record setting 12 year manage filming vital song without meenas close ups meena kumari lady lead role terminally ill fighting life early 1971',
 'people especially young people may understand film look like story loss actually story alone people may never feel loneliness levelbr br cheadles character johnson reflected total opposite sandlers character fineman johnson felt trapped blessing fineman trying forget life perspective jada wonderful additive cast sandler pull tear cheadle comic role great supporter sandlerbr br see oscar somewhere fine film ever lost felt alone film assure youre alonebr br jerry',
 'soylent green one best disturbing science fiction movie 70 still persuasive even today standard although flawed little dated apocalyptic touch environmental premise typical time still feel unsettling thoughtprovoking film qualitylevel surpasses majority contemporary sf flick strong cast intense sequence personally consider classic new york 2022 depressing place alive overpopulation unemployment unhealthy climate total scarcity every vital food product form food available synthetic distributed soylent company charlton heston great shape play cop investigating murder one soylents eminent executive stumble upon scandal dark secret script little oversentimental time climax doesnt really come big surprise still atmosphere tense uncanny riotsequence truly grueling easily one macabre moment 70 cinema edward g robinson ultimately impressive last role there great modest supportive role joseph cotton baron blood abominable dr phibes sciencefiction book nightmarish inevitable fade humanity fancy spaceship hairy monster attacking planet',
 'michael stearns play mike sexually frustrated individual interesting moral attitude towards sexuality problem ogling naked dancer woman start sex men thats loses belief woman actually sex thats lose sense innocence andor beauty stroll hollywood hill stalking lovemaking couple distance ultimately shooting men dead highpowered rifle scopebr br seeming primary reason movie existence indulge sexual activity story come afterthought bound make many happily heterosexual male quite pleased treated enough protracted scene nudity lady look awfully good sans clothes sex serve major dose titillation course seeing fair deal scope ups creepiness factor considerably illustrates compulsion towards voyeurism one thing mike eye couple scope minute time finally pulling trigger underscored awfully intrusive somewhat atmospheric music soundtrackbr br penchant lurid trash bound enjoy one degree another even includes one lesbian tryst confounds mike render uncertain react unfolds slow pace wrap amusing ironic twist kinky twisted rarity nothing else going definitely keep viewer glued screenbr br 710',

In [19]:
type(corpus)

list

In [20]:
corpus[0:2]

['stuff going moment mj ive started listening music watching odd documentary watched wiz watched moonwalker maybe want get certain insight guy thought really cool eighty maybe make mind whether guilty innocent moonwalker part biography part feature film remember going see cinema originally released subtle message mjs feeling towards press also obvious message drug bad mkaybr br visually impressive course michael jackson unless remotely like mj anyway going hate find boring may call mj egotist consenting making movie mj fan would say made fan true really nice himbr br actual feature film bit finally start 20 minute excluding smooth criminal sequence joe pesci convincing psychopathic powerful drug lord want mj dead bad beyond mj overheard plan nah joe pescis character ranted wanted people know supplying drug etc dunno maybe hate mjs musicbr br lot cool thing like mj turning car robot whole speed demon sequence also director must patience saint came filming kiddy bad sequence usually director hate working one kid let alone whole bunch performing complex dance scenebr br bottom line movie people like mj one level another think people stay away try give wholesome message ironically mjs bestest buddy movie girl michael jackson truly one talented people ever grace planet guilty well attention ive gave subjecthmmm well dont know people different behind closed door know fact either extremely nice stupid guy one sickest liar hope latter',
 'classic war world timothy hines entertaining film obviously go great effort length faithfully recreate h g well classic book mr hines succeeds watched film appreciated fact standard predictable hollywood fare come every year eg spielberg version tom cruise slightest resemblance book obviously everyone look different thing movie envision amateur critic look criticize everything others rate movie important baseslike entertained people never agree critic enjoyed effort mr hines put faithful hg well classic novel found entertaining made easy overlook critic perceive shortcoming']

In [21]:
corpus[0]

'stuff going moment mj ive started listening music watching odd documentary watched wiz watched moonwalker maybe want get certain insight guy thought really cool eighty maybe make mind whether guilty innocent moonwalker part biography part feature film remember going see cinema originally released subtle message mjs feeling towards press also obvious message drug bad mkaybr br visually impressive course michael jackson unless remotely like mj anyway going hate find boring may call mj egotist consenting making movie mj fan would say made fan true really nice himbr br actual feature film bit finally start 20 minute excluding smooth criminal sequence joe pesci convincing psychopathic powerful drug lord want mj dead bad beyond mj overheard plan nah joe pescis character ranted wanted people know supplying drug etc dunno maybe hate mjs musicbr br lot cool thing like mj turning car robot whole speed demon sequence also director must patience saint came filming kiddy bad sequence usually director hate working one kid let alone whole bunch performing complex dance scenebr br bottom line movie people like mj one level another think people stay away try give wholesome message ironically mjs bestest buddy movie girl michael jackson truly one talented people ever grace planet guilty well attention ive gave subjecthmmm well dont know people different behind closed door know fact either extremely nice stupid guy one sickest liar hope latter'

VECTORIZATION

In [22]:
#using the bag of words to vectorize the text data
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,2))
traindata = cv.fit_transform(corpus)
X = traindata
y = data_reduced.sentiment

In [23]:
X.dtype

dtype('int64')

In [24]:
#using random forest for classification
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X,y)

RandomForestClassifier()

In [25]:
#predicting the outputs using the model
from sklearn.metrics import accuracy_score
y_pred = clf.predict(X)
accuracy_score(y, y_pred)

1.0

In [26]:
y.dtype

dtype('int64')

In [27]:
#writing a function to classify the input text sentiment analysis
def find_sentiment(input_text):
  input_vector = cv.transform(preprocess(input_text))
  prediction = clf.predict(input_vector)
  if prediction == 0:
    print('Input statement has negative sentiment')
  if prediction == 1:
    print('Input statement has Positive sentiment')

In [28]:
input = ["i hate avengers movie"]

In [29]:
#chekcing whether the model is working fine
find_sentiment(input)

Input statement has negative sentiment

In [40]:
#importing the decision treee classifier
from sklearn.tree import DecisionTreeClassifier

In [41]:
#making instance for decision tree classifier
clf2 = DecisionTreeClassifier (criterion='entropy')

In [42]:
#fitting the decision tree classifier
clf2.fit(X,y)

DecisionTreeClassifier(criterion='entropy')

In [43]:
#doing the prediction for the decision tree
y_pred = clf.predict(X)

In [44]:
accuracy_score(y, y_pred)

1.0

DEEP LEARNING

In [30]:
X.shape

(200, 28880)

In [31]:
# converting so that we can use X1 in the RNN
X1 = X.toarray()

In [32]:
max_length = max([len(x) for x in X1])

In [33]:
max_length

28880

In [34]:
len(X1[0])

28880

In [35]:
#importing the necessary libraries
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Embedding,SimpleRNN,Dropout
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [38]:
#creating the model
model = Sequential()
model.add(Embedding(input_dim = 20000, output_dim=150, input_length=300))
model.add(SimpleRNN(128,dropout=0.2)) #to prevent overfitting
model.add(Dense(1,activation='sigmoid'))
model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_2 (SimpleRNN)             │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [39]:
#compiling the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

COMPARISON: both Random Forest classifier model and decision tree model are working great with accuracy of 1